name: Update README with latest blog posts
on:
  schedule:
    # Roda a cada 4 horas
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Update README with blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          # URL do feed RSS do seu blog ou YouTube.
          # Para YouTube, use: https://www.youtube.com/feeds/videos.xml?channel_id=SEU_CHANNEL_ID
          # Para Medium, use: https://medium.com/feed/@seu-usuario
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=SEU_CHANNEL_ID"
          
          # Outras configurações
          max_post_count: 5 # Número de posts a serem listados
          readme_path: './README.md'
          comment_tag_name: "BLOG-POST-LIST"
          date_format: "dd/mm/yyyy"
