name: Update README with latest YouTube videos
on:
  schedule:
    # Roda a cada 4 horas
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Update README with YouTube videos
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          # URL do feed RSS do canal DEVANDRE no YouTube
          feed_list: "https://www.youtube.com/watch?...8"
          
          # Outras configurações
          max_post_count: 5 
          readme_path: './README.md'
          comment_tag_name: "BLOG-POST-LIST"
          date_format: "dd/mm/yyyy"
